### ISSUE TITLE
Next/Fixtures cogs are broken

### ISSUE THREAD

**Issue by reddit-tennis** [AndyReifman/ArseneWenger#95]
Stacktrace:

```Traceback (most recent call last):                                                                      
  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore                    
  File "/arseneWenger/cogs/fixtures.py", line 55, in next                                               
    fixtures = parseFixtures()
  File "/arseneWenger/cogs/fixtures.py", line 177, in parseFixtures
    matches = table.findAll("article",attrs={'role':'article'})
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by reddit-tennis** [comment]
Demonstrated a fix in #94  (will re-do PR tomorrow or so, as commits are a bit fuzzy)

![image](https://github.com/AndyReifman/ArseneWenger/assets/38725593/fea685ec-e28b-42ca-a052-8f0de583c76d)

Details in:

https://github.com/AndyReifman/ArseneWenger/pull/94/commits/081e77e59d253f356c190d1b517dde4e1187b3b9
